# fly.toml app configuration file generated for foto-bot on 2023-06-24T21:46:32+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "foto-bot"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  PRIMARY_REGION = "ams"